### ISSUE TITLE
XOSP-N (7.1.1)

### ISSUE THREAD

**Issue by Spookcity** [Spookcity/ROMS-G800F#16]
Here you can share your experiences with XOSP-N. The idea behind XOSP is a minimal bloat free ROM which includes Sony Xperia specific apps and various tweaks users would expect from a custom ROM.

There's no XDA thread currently. Perhaps soon! This will be updated appropriately.

**Comment by ghost** [comment]
You don't have to leave a comment to subscribe to the thread :) (I thought so at first but it isn't true)

**Comment by Spookcity** [comment]
@StanNL Updated and removed that part. Thanks!

**Comment by Mikahlo** [comment]
Hi there!
XOSP is the perfect ROM for me. Smooth without animation scale reduced, no bloatware and a nice design. The customization options are between a slimROM and a standard ROM, nothing special but just enough. I even use the launcher that comes with it. Thanks for building this!

**Comment by Spookcity** [comment]
@Mikahlo Hey,thanks for joining in.  I'm glad you like it.  Hope you enjoy!

**Comment by Mikahlo** [comment]
Some more words on my new favourite ROM after a couple of days of usage:
I love it! Generally speaking this ROM "feels different" and "fresh". Maybe everyone should "xperiance" this^^
The status bar icons are slightly tweaked and just look good. The phone signal and the wlan indicator are divided into 4 segments each to represent the signal strength. Even the battery icon looks beautiful and shows a battery with the capacity in percent in it.
The quick settings menu is pitch black instead of grey / brownish/ green like on the other ROMS.
On the home screen you can swipe down to instantly search for apps. The launcher that comes with the ROM allows to use folders but doesn't have any special features other than that.
The battery lifetime is great as well as the screen on time. Everything is smooth and fast with this build as it is, without any tweaks.
@Spookcity : Are 4 GB of RAM sufficient to build an android ROM or are 8 GB the absolutely minimum?
Aaaand thanks again :+1:

**Comment by Spookcity** [comment]
@Mikahlo Glad you like the ROM! I used it for awhile and I liked it as well. I agree that it just has a different feel to it and it is nice!

On building: I build with 4gb of RAM. You need to tweak some things in order to achieve this,but it will work. It will obviously take a fair bit of time to build. You also MUST have a minimum 4gb of swap as well. I have 4.5.
If you are looking at building just send me a message or something on XDA and I can tell you the things needed to be able to build with 4GB.

**Comment by ghost** [comment]
@Mikahlo Well, to be honest, I'm not a fan of the UI at all. I did use a Sony phone back in the Android Jellybean days and the UI hasn't really improved since then, to be honest. I prefer BeanStalk's UI, but you can't have everything in a ROM, so XOSP is still my favourite ROM at the moment. 

In my opinion the battery life isn't great either, but I used L Speed and put every setting on extreme performance, so I shouldn't have had high expectations.


I like the launcher and I think it definitely has some good features. Have you even looked at the settings? ;)
You can set icon packs and enable the Google Now page, which are things most stock launchers can't do. 
Also, the launcher definitely plays a major role in the fluidity of the ROM, so I take the lack of personalisation features for granted.

@Spookcity Really? Only 4GB? My PC has eight and I always thought mine was pretty bad. But RAM isn't everything, right? What's your clock speed?

**Comment by Spookcity** [comment]
@StanNL Yep,I wish I had more than 4GB of RAM,but it does work at least. The CPU doesn't get much better. Its a core 2 quad @ 2.0GHZ. It's a 6 or so year old Acer, so yeah lol
Hell,I have a desktop that's rockin a Celeron D from about 2005. Its only used as a media server though.
A more modern laptop is def on my want-list.

**Comment by ghost** [comment]
@Spookcity Well my CPU is worse than yours. It is a quad core 1.5 GHz processor (I'm unsure which one) so it is not very fast, but the heaviest task I do is web development...

**Comment by Spookcity** [comment]
@StanNL Ahh,OK. Well I don't feel so bad then hehe. That's the important thing though,that the PC can handle the tasks you need it to. At this point mine does,albeit slowly. Android is by far the most taxing thing I do on my PC. I do some music stuff as well,but it handles that pretty well. All in all I'm very happy with my 6 year old Acer. It just takes far too long to build android.

**Comment by ghost** [comment]
@Spookcity Yeah but I do have 8GBs of RAM so I can use Chrome development tools on multiple tabs, without Chrome eating all of my RAM. That is pretty rare for Google Chrome these days.

I have a 6 year old Acer as well, by the way, but it is a (pretty bulky) laptop and not a desktop.

**Comment by Spookcity** [comment]
@StanNL Yes, I use chromium and while I don't do any web development, it uses massive amounts of RAM. I really like chrome/chromium,but man its a RAM hog!
I also have a rather bulky Acer laptop.

**Comment by ghost** [comment]
@Spookcity Really, which laptop do you have?

**Comment by Spookcity** [comment]
@StanNL [Aspire 7738](https://www.notebookcheck.pl/fileadmin/_migrated/pics/1_64.jpg)

You?

**Comment by ghost** [comment]
@Spookcity I have no clue because Acer isn't very good at giving remarkable names, as you know.

I think it's this one: https://ic.tweakimg.net/ext/i/1329919511.jpeg

**Comment by Spookcity** [comment]
@StanNL That is very true. Both yours and mine were probably released not too far apart. I really like mine,but it's huge for a laptop. Its not very portable, but there is a horrible design flaw in the 7738,which makes mine completely not portable. The DC power jack is placed in a circular portion where the screen attaches,so it tends to break due to movement. I've replaced it twice already and now I've just gone ahead and cut the wires and hardwired it with electrical tape. Hehe. Not sure how much longer its gonna last for me. I need to be careful with it,but I'm not spending another 20 euros or so on another one!
I don't know what Acer was thinking with this particular design. Yours doesn't have that,which is def good!

**Comment by ghost** [comment]
Well mine isn't very portable either. Not only is it 3.3kg, but there is definitely something wrong with its battery. I have no clue why, but it only lasts for like 10 minutes off-charger, so I can only use it within my own house. It only has a 4000 mAh battery so I don't think it was even meant to be used that way. 

Something I did find out, is the fact that, although my 'max' clock speed is 1.5 GHz, the average clock speed was around 2.2 GHz, which is odd since I don't remember overclocking it...

Your laptop was released in 2009 and mine in 2011, but there have been some huge visual changes in terms of design in my opinion.

**Comment by Spookcity** [comment]
@StanNL Ahh,OK so mine is a fair bit older. Yours I'm sure runs much better with double the RAM and especially if you're getting 2.2GHZ clock speeds. My battery is broken as well,but as mentioned it doesn't matter. I just have an electrical taped wire coming out of where I would normally plug in the charger anyway. It looks awful,but it works. Haha
If this design flaw wasn't there I would upgrade the RAM to 8GB as well as I believe its capable, but it just isn't worth it at this point with my homemade wiring job. Both laptops do look very similar. The one obvious difference is where your charger plugs in. Acer apparently figured out what a disaster of a design that was.

**Comment by ghost** [comment]
@Spookcity Haha well at least they learned from their mistakes

**Comment by ghost** [comment]
@Spookcity By the way: I don't think they look visually similar at all

**Comment by Spookcity** [comment]
@StanNL Really? I thought they looked very similar. Minus the somewhat strange audio related features on mine (that I've never used) ..And again the DC jack placement.

Edit: After another glance they are more visually different than I first thought.

**Comment by Mikahlo** [comment]
I have an Asus K52J from around 2010 or 2011. An old core i5 with up to 2,4 Ghz, an mobility radeon card and only 4 GB of RAM. The fastest part inside this thing is the superb ssd 840 series from samsung with 250 GB.

**Comment by Spookcity** [comment]
@Mikahlo You're computer is also way better than mine :( 
Lol. Hell, I think my hard drive is only 5400 rpm.Probably time I start looking into another one. Especially with my "rigged" power connection.
