### ISSUE TITLE
Dialer BUG

### ISSUE THREAD

**Issue by Guntzog** [Spookcity/ROMS-G800F#17]
Hello,

Am facing a new Bug i have no idea how it happened.

When i call a number with The AOSP dialer, The screen turns black and no action possible, except ending the call (able to do that with the Power button Call end), i was thinking that it was a ROM RR N bug at the beggining, Flasher another MM, Liquid and BeanStalk... Same Bug, re-downloaded Rom, Full Data system Cash.. Wipe Clean Flash, still the same, Any suggestions ?

**Comment by ghost** [comment]
I think that's because the screen gets "blocked" when calling, so that you don't accidentally press any buttons with your cheek when holding the phone to your ear.
The device shouldn't always block the display, but only when there's something (probably the side or your head) nearby. It checks that using the proximity sensor, which is one of the black dots on the top of your phone.  When that sensor detects an object within very close range, your phone screen will turn black and you can't touch anything.
Having that said, this is most likely the "issue" you're talking about. So in order to solve it, you need to make sure nothing is blocking the proximity sensor. You shouldn't place your finger (or head) there and if that doesn't solve the issue for you, try cleaning the sensor.

**Comment by Guntzog** [comment]
It is so clean, do you think i should take the Cover Glass off ?

**Comment by Spookcity** [comment]
@Guntzog I highly recommend not doing that. It's not so easy and there should be no need in this situation. I'm not sure what else could be causing this problem. I'll think some on it, but what @StanNL said really sounds to me like it should be the solution.

**Comment by Guntzog** [comment]
i can not think of something else triggering the proximity sensor, it's so Clean, if it is not the Screen Protection Glass (shield) then what else ? Hw problem ?

**Comment by Spookcity** [comment]
@Guntzog Perhaps,I'm unsure. Grab a log for me while having this problem and I'll have a look. Although I don't really expect to see anything,but who knows.

**Comment by ghost** [comment]
@Guntzog Try installing a "Proximity sensor check" app.

**Comment by Guntzog** [comment]
EDIT : I reset the sensor and force closed it now am good, thanks so much guys

![screenshot_20170520-164804](https://cloud.githubusercontent.com/assets/28767865/26277053/ad16af0a-3d84-11e7-9de1-59355d5b3479.png)

**Comment by ghost** [comment]
@Guntzog https://play.google.com/store/apps/details?id=com.tigermonster.proxfinder
Try this app and see if it properly alternates between 0 and 5 cm when you move your finger away from and towards the sensor

**Comment by ghost** [comment]
And? What are your results?

**Comment by Guntzog** [comment]
@StanNL I edited the post with the photo, I used it, the app accidentally FC'ed and asked me tobreset the Prox sensor and restartedbsys UI, and after that all became good

**Comment by ghost** [comment]
@Guntzog Well: as long as it works, right?

**Comment by Guntzog** [comment]
Yess, it was weird but I think as you sad, the distance was set too close and the app reseted it to default 5cm, now am happy :D
